import './icon.css'

export * from './add'
export * from './arrow-back'
export * from './arrow-forward'
export * from './bin'
export * from './close'
export * from './dots-horizontal-triple'
export * from './eye'
export * from './eye-blocked'
export * from './menu'
export * from './pencil'
export * from './pokerBola'
export * from './search'
export * from './spinner'
